// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Image struct {
	Original  *string `json:"original,omitempty"`
	Small     *string `json:"small,omitempty"`
	Thumbnail *string `json:"thumbnail,omitempty"`
}

type Product struct {
	ID                   string  `json:"id"`
	Sku                  string  `json:"sku"`
	Brand                string  `json:"brand"`
	Name                 string  `json:"name"`
	Colorway             string  `json:"colorway"`
	Gender               string  `json:"gender"`
	Silhouette           string  `json:"silhouette"`
	ReleaseYear          string  `json:"releaseYear"`
	ReleaseDate          string  `json:"releaseDate"`
	RetailPrice          int     `json:"retailPrice"`
	EstimatedMarketValue int     `json:"estimatedMarketValue"`
	Story                *string `json:"story,omitempty"`
	Image                *Image  `json:"image,omitempty"`
}

type Query struct {
}
